# Generated by Django 5.2.8 on 2025-12-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phono_number',
            new_name='phone_number',
        ),
    ]
