# Generated by Django 5.2.8 on 2026-02-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='store.favorite'),
        ),
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='review_videos/'),
        ),
    ]
